name: Build, Test and Deploy Library App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependecies
      run: npm install
    - name: Install Playwright Browser
      run: npx playwright install
    - name: Start the Back-End &
      run: npm run server
    - name: Start Front-End &
    - run: npm run start
    - name: Run UI Tests
      run: npm test
